language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0

before_install:
    - composer self-update

install:
    - composer install --prefer-source
